version: "3"
services:
  app:
    image: nodeimage
    container_name: nodeserver
    build: ./
    restart: always
    ports:
    - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
