version: "3"
services:
  app:
    image: iptrack-img
    container_name: iptrack-img
    build: ./
    restart: always
    ports:
    - "8080:8080"
    environment:
      - REDIS_HOST=172.10.0.7
      - REDIS_PORT=6379
